FROM php:8.1.0-apache

RUN adduser  desa
RUN mkdir /home/desa/.ssh
RUN chown -R desa:desa /home/desa/
RUN echo "StrictHostKeyChecking no" >> /home/desa/.ssh/config
RUN apt-get -y update --fix-missing \
	&& apt-get upgrade -y \ 
	&&  apt-get -y install apt-utils nano wget dialog net-tools dnsutils sudo \
	&& apt-get -y install --fix-missing apt-utils build-essential git curl libcurl4 libcurl4-gnutls-dev zip libxml2-dev \
	libwebp-dev \
    libjpeg62-turbo-dev \
    libpng-dev libxpm-dev \
    libfreetype6-dev \
    && apt update \
    && apt install -y git acl openssl openssh-client wget zip sudo \
    && apt install -y libpng-dev zlib1g-dev libzip-dev libxml2-dev libicu-dev openssl apache2 \
    && docker-php-ext-install intl pdo zip \
    && docker-php-ext-install pdo_mysql \
    && apt install -y libpq-dev \
    && docker-php-ext-install pdo_pgsql \
    && docker-php-ext-install bcmath sockets \
    && apt install -y librabbitmq-dev vim libssh-dev \
    && pecl install amqp-1.11.0RC1 \
    && docker-php-ext-enable --ini-name 05-opcache.ini opcache  amqp \
	&& adduser www-data sudo \
	&& adduser desa sudo \
	&& adduser www-data sudo \
	&& echo 'desa:desa' | chpasswd \
	&& echo 'root:root' | chpasswd \
	&& echo 'www-data:root' | chpasswd  \
	&& mkdir /etc/apache2/ssl \
	&& openssl req -new -x509 -days 3650 -subj "/C=AR/O=jkober.ddns.net/CN=jkober.ddns.net" -nodes -out /etc/apache2/ssl/ssl1.crt -keyout /etc/apache2/ssl/ssl1.key \
	&& chown -R root /etc/apache2/ssl/ \
	&& chgrp -R root /etc/apache2/ssl/ \
	&& chmod -R 600 /etc/apache2/ssl/ \
	&& mkdir -p /var/run/apache2/ \
	&& a2enmod rewrite headers \
	&& a2enmod ssl \
	&& apt install -y npm nodejs \ 
	&& npm install --global yarn \
	&& curl https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer \
	&& composer self-update \
	&& wget https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer \
	&& chmod a+x php-cs-fixer \
	&& mv php-cs-fixer /usr/local/bin/php-cs-fixer \
	&& echo 'deb [trusted=yes] https://repo.symfony.com/apt/ /' | sudo tee /etc/apt/sources.list.d/symfony-cli.list \
	&& apt-get -y update --fix-missing \
	&& apt install symfony-cli \
	&& git config --global user.email "jkober@santafe.gov.ar" \
	&& git config --global user.name "jose" \
	&& apt install -y default-mysql-client\
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \ 
	&& docker-php-ext-install -j$(nproc) gd	\
	&& apt-get install libxml2-dev 	\
	&& docker-php-ext-install soap  	\
	&& docker-php-ext-enable soap	\
	&& apt-get install -y  iputils-ping
	run pecl install xdebug
	run docker-php-ext-enable xdebug
	run  apt-get install -y imagemagick
	
	run apt-get update && apt-get install -y \
    libmagickwand-dev --no-install-recommends \
    && pecl install imagick \
	&& docker-php-ext-enable imagick \
	
	&& apt install -y libfreetype6-dev gsfonts   
  
		run  sudo apt-get install -y  iputils-ping
	run apt install -y ghostscript
	run docker-php-ext-install exif
	
#	RUN pecl install imagick
	WORKDIR /var/www/html/
EXPOSE 9003
EXPOSE 9000
EXPOSE 443
EXPOSE 80
